### PR TITLE
Activate & merge accounts for fiyin

### PR DESCRIPTION
**Pull request by luxumbra**
- also made some edits to the README to better reflect the process.

Would appreciated a sanity check on the README update. I have added a step for when we need to activate players (Step 6) and I dunno if it belongs in the flow of the distribution, needs to be in a separate section or just isn't required. @s-ben is Step 6 necessary? 

Due to the broken `yarn start` we can't re-run the scores locally after activation, so seems we need to push and merge to master and allow the github actions to run again to be able to get the updated scores. Am i over complicating it? Many TIA. 🙏🏻

### CODE REVIEW

**Review by alalonde — APPROVED** [review]
Yeah looks good. If loading the data is not working locally, then yes, unfortunately you will have to push and merge a PR and then wait up to a whole day to see the new calcs

**Comment by luxumbra** [comment]
@alalonde, thanks for the merge. I'll come back tomorrow (if it runs successfully lol) and finish the distribution.

**Comment by s-ben** [comment]
I may be wrong, but I think you can recalculate the scores locally without using `yarn start`. It's been a while since I've done it (and should be tested) but I think you can run `yarn graph` (re-calculates contribution graph from raw data), then `yarn credrank` (caulculates Cred scores from contribution graph). This is actually how we used to do it before we created `yarn start`, which bundled these commands for convenience. 

Since the README instructions tell you to download the latest data from the remote instance (`gh-pages`), you should be able to use that latest data to recalculate scores and do grain payouts locally, without having to push an intermediat PR to trigger the GH action remotely. My understanding (from crappy memory😓  ), was that we were pushing the PR previously because `yarn load` wasn't working locally, but was remotely using the GH action. However, if you have the latest raw data from `gh-pages`, you should have everything you need to activate contributors, recalculate scores, and do grain distribution. Fwiw, the Cred scores shouldn't change unless you merge identities. So you can activate/inactivate players without changing Cred scores and affecting distributions, as long as you're not merging identities, which will necessitate recalculating scores. 

Hope that is helpful. It's possible the easiest way to do it is just the way you're doing it, pushing changes to remote and doing the calculation there.

**Comment by alalonde** [comment]
That's a good point. If we're merely merging identities, then we shouldn't need to reload the data. The test would be to try it without reloading, computing the cred, then pushing, waiting 24h, then pulling and computing cred again.

**Pull request merged**
